# # Fix data errors in rr_attempts_minted
# clean_rr_attempts_minted <- function(rr_attempts_minted) {
#   rr_attempts_minted %>%
#     # Some of the minted projects didn't get assigned an is_HSR value. 
#     # Manually assign those values here
#     mutate(is_hsr = case_when(rr_id %in% c("996g", 
#                                            "19y4", 
#                                            "8z81",
#                                            "2y2g",
#                                            "927",
#                                            "9y8y",
#                                            "5196",
#                                            "2z3g",
#                                            "2g5g",
#                                            "2637",
#                                            "8zz7",
#                                            "y7g1",
#                                            "0y68",
#                                            "yk20",
#                                            "5738",
#                                            "m7k3",
#                                            "2yyg",
#                                            "9y2g",
#                                            "6557",
#                                            "gyg1",
#                                            "6547",
#                                            "4zz0",
#                                            "0056",
#                                            "94ky",
#                                            "3g4k",
#                                            "329k",
#                                            "y791",
#                                            "756g",
#                                            "95my",
#                                            "6g7k",
#                                            "4968",
#                                            "68",
#                                            "m47",
#                                            "ykg6") ~ "Non-HSR",
#                               rr_id %in% c("8g1", 
#                                            "99gy", 
#                                            "8m71", 
#                                            "618k", 
#                                            "9ky", 
#                                            "k17", 
#                                            "m5y9", 
#                                            "528",
#                                            "618",
#                                            "y2312",
#                                            "20g",
#                                            "g7g1",
#                                            "4z02",
#                                            "g9mm",
#                                            "999g",
#                                            "m7y9",
#                                            "99m7",
#                                            "99yg",
#                                            "k144",
#                                            "8m17",
#                                            "m5m7",
#                                            "556",
#                                            "z189",
#                                            "548",
#                                            "7976",
#                                            "1y22",
#                                            "3zz",
#                                            "0y08",
#                                            "wz9",
#                                            "g941",
#                                            "y01",
#                                            "4182",
#                                            "0m7",
#                                            "8g91",
#                                            "356",
#                                            "y50") ~ "HSR",
#                               .default = is_hsr))
# }
# 

